@echo off
echo Starting Unified IT Support System...

echo Starting Backend...
start "Backend" cmd /k "cd backend && python simple_main.py"

echo Waiting for backend to start...
timeout /t 5 /nobreak > nul

echo Starting Frontend...
start "Frontend" cmd /k "cd frontend && npm start"

echo Both services are starting...
echo Backend will be available at: http://localhost:8000
echo Frontend will be available at: http://localhost:3000
echo.
echo Press any key to exit...
pause > nul
